### ISSUE TITLE
请问embedding是什么操作？

### ISSUE THREAD

**Issue by Wchenguang** [Konilgkms/2020_DCIC_TianChi#1]
请问embedding操作是什么啊，查了很多都是nlp里的。

**Comment by Konilgkms** [comment]
你好～不好意思呀，才看到信息。embedding的操作其实就是从nlp中转变来的，将类别特征看作词一样进行训练。可以试着搜索category embedding的相关资料。

**Comment by Wchenguang** [comment]
谢谢啦！
